CREATE DATABASE IF NOT EXISTS aiven;
USE aiven;

CREATE TABLE IF NOT EXISTS koduser (
  uid INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  balance DECIMAL(15, 2) DEFAULT 100000.00,
  phone VARCHAR(50),
  role VARCHAR(50) DEFAULT 'customer'
);

CREATE TABLE IF NOT EXISTS usertoken (
  tid INT AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(1000) NOT NULL,
  uid INT NOT NULL,
  expiry DATETIME NOT NULL,
  FOREIGN KEY (uid) REFERENCES koduser(uid) ON DELETE CASCADE
);
